### ISSUE TITLE
Kanji are not recognised 

### ISSUE THREAD

**Issue by blacksparrow123** [CaptainDario/DaKanji#14]
Hello, 
I'm on android and using v.2.0.1.
Upon drawing any kanji I'm only getting あ in recommendation.
![IMG_20220628_104735](https://user-images.githubusercontent.com/37986014/176123568-e38aa901-0572-4fda-8449-7a8f60489520.jpg)

**Comment by CaptainDario** [comment]
Hey @blacksparrow123 ,

Thank you for taking the time to open an issue. I assume that there is an error with Tensorflow initialization on your phone. That's most likely related to your phone.
I am gonna take a closer look, but your exact android version and phone would be helpful for debugging this.

Cheers 
Dario

**Comment by blacksparrow123** [comment]
Xiaomi Redmi Note 8 Pro
Android 10 QP1A.19711.090

**Comment by CaptainDario** [comment]
It uses a MediaTek processor that already made problems in the past. I am gonna take a look in the coming days.

**Comment by blacksparrow123** [comment]
Thank you

**Comment by CaptainDario** [comment]
@blacksparrow123 I have a made [dev build](https://github.com/CaptainDario/DaKanji/releases/tag/dev).
Can you try installing it and go to `settings -> advanced -> inference backends`, set it to CPU and restart the app?

Let me know if that helped.

**Comment by blacksparrow123** [comment]
Works like a charm

**Comment by blacksparrow123** [comment]
I tried Takoboto and Aedict.
In both cases nothing happened.

Thanks for your work!
NP

**Comment by CaptainDario** [comment]
@blacksparrow123  I fixed this problem too. Can you try the [new release](https://github.com/CaptainDario/DaKanji/releases/tag/dev)?

**Comment by blacksparrow123** [comment]
@CaptainDario 
Takoboto works.
For aedict it says that it's not installed.

**Comment by CaptainDario** [comment]
I am gonna take a look at it. I guess they changed something about aedict as I didn't change my code around it (I believe).

**Comment by CaptainDario** [comment]
@blacksparrow123 I finally found the problem with aedict and fixed it. Gonna publish a new release (2.1) soon. In the meantime, you can get a working version [here](https://github.com/CaptainDario/DaKanji/releases/tag/dev).

I am gonna ping you once it is officially released. Mind you if I ask if you would become a tester for upcoming DaKanji releases? Later this year will come a major update with big new features...

**Comment by blacksparrow123** [comment]
@CaptainDario 
Aedict works.
Many thanks.
I probably be capable to provide feedback only from time to time.

**Comment by CaptainDario** [comment]
@blacksparrow123 thanks for confirming that it works.
There will only be like 2-3 releases per year and if you only have time to look at one that's fine. But if you don't want to, that's fine too.

Closing this as fixed.
