### ISSUE TITLE
Says aedict is not installed even though it is

### ISSUE THREAD

**Issue by bitspittle** [CaptainDario/DaKanji#16]
How does the check work which detects an installed app?

I have aedict installed (https://play.google.com/store/apps/details?id=sk.baka.aedict3) but DaKanji doesn't seem to recognize it

**Comment by CaptainDario** [comment]
Hey @bitspittle ,
This issue was ready fixed. However, life got busy and I didn't had the time to publish the fix on the PlayStore. You can manually install it from [here](https://github.com/CaptainDario/DaKanji/releases/tag/dev)

**Comment by CaptainDario** [comment]
Closing this as seemingly fixed
