### ISSUE TITLE
"what's new" screen on every app start 

### ISSUE THREAD

**Issue by atomicptr** [CaptainDario/DaKanji#17]
Every time I open the app the "what's new" screen is showing up and it's a tad bit annoying. 

OS: Android 13 

![Screenshot_20220911-171816.png](https://user-images.githubusercontent.com/674705/189535454-01db9106-7130-4f92-b510-13e1fa0c6d70.png)

**Comment by CaptainDario** [comment]
Hey @atomicptr 
thank you for the report.
I am quite clueless what could be the reason, could you try installing the latest dev version from [here](https://github.com/CaptainDario/DaKanji/releases/tag/dev) and let me know if that fixes your problem?

**Comment by atomicptr** [comment]
Looks like that version does not have this issue

**Comment by CaptainDario** [comment]
Thank you for the quick feedback. Gonna close this issue but if you notice that the behavior is still there feel free to reopen.
