### ISSUE TITLE
How to use this model in kotlin?

### ISSUE THREAD

**Issue by NCheng8835** [CaptainDario/DaKanji#20]
This handwriting recognition model is very good. I want to use this model to develop an APP for learning Japanese. However, I do not know how to use it in kotlin, because I have no experience in machine learning.I hope you can give me a kotlin example->how to convert bitmap data into model input data, thank you very much.

**Comment by CaptainDario** [comment]
Hey, I am not sure what you mean. This is the repo for the Japanese learning app "DaKanji".

I guess you mean the [character CNN](https://github.com/CaptainDario/DaKanji-Single-Kanji-Recognition).
In the [inference section](https://github.com/CaptainDario/DaKanji-Single-Kanji-Recognition#inference) it is explained how to use it. However, how inference can be run in kotlin, I do not know. If you have questions about something specific to the model, please do not hesitate to ask in the mentioned repo.

Good luck on your app!

**Comment by NCheng8835** [comment]
I am sorry that I did not see the closed issue, thank you very much.

**Comment by CaptainDario** [comment]
> I am sorry that I did not see the closed issue, thank you very much.

@NCheng8835  No worries! The code snippet is in kotlin? I will add a new section to the repo with usage of the model in different languages, and would include kotlin

**Comment by NCheng8835** [comment]
It works[https://github.com/CaptainDario/DaKanji-Single-Kanji-Recognition/issues/1#issuecomment-907814054](url),thanks again.

**Comment by NCheng8835** [comment]
@CaptainDario It works,thanks again. #https://github.com/CaptainDario/DaKanji-Single-Kanji-Recognition/issues/1#issuecomment-907814054

**Comment by CaptainDario** [comment]
@NCheng8835 thanks!
I added it https://github.com/CaptainDario/DaKanji-Single-Kanji-Recognition/wiki#usage-in-different-languages
