### ISSUE TITLE
Re-entering draw mode does not clear search

### ISSUE THREAD

**Issue by kirawi** [CaptainDario/DaKanji#73]
It makes it a little tedious since you have to delete the search query and then delete the saved kanji in the drawing bar in order to do anything. I think it would be better if the kanji bar represented the contents of the search bar as well.

**Comment by CaptainDario** [comment]
Hey, thanks for the issue!

Yes, you are right. When reentering the kanji drawing mode, the kanji-bar should either be empty or show the dictionaries searchbar content. I guess I will always clear it when opening the drawing screen.

You just missed the v3.3 release for this feature request (released v3.3 yesterday). So it's gonna take some time for a new version.

**Comment by kirawi** [comment]
I think representing the search content would be better in case you accidentally enter drawing mode from the kanji lookup.

**Comment by CaptainDario** [comment]
> I think representing the search content would be better in case you accidentally enter drawing mode from the kanji lookup.

I think I don't understand you. What is the kanji lookup?

**Comment by kirawi** [comment]
The search bar for words I mean
