### ISSUE TITLE
Kanji tab starts scrolled part-way down

### ISSUE THREAD

**Issue by ethanmcc** [CaptainDario/DaKanji#95]
When I search for a word and click into the kanji tab, it seems to maintain the same scroll height as the last term I looked at in the kanji tab. This is unexpected, as I’m expecting to be at the top of the scroll space when I load a new term.

**Comment by CaptainDario** [comment]
Thank you for raising this issue! I think you are right.

I will look into it and try to implement it for v3.5

**Comment by CaptainDario** [comment]
@ethanmcc this should be fixed in the next minor release 3.4.1. If you still experience it let me know.
