### ISSUE TITLE
The app doesn't open on Windows

### ISSUE THREAD

**Issue by Danielshmaniel** [CaptainDario/DaKanji#98]
It's a shame that I wasn't able to use DaKanji on my Windows 10 PC. I would like a convenient offline Japanese dictionary app but when I install this using Microsoft Store and run the app I get a blank white window and it closes immediately.

**Comment by CaptainDario** [comment]
Hey, thank you for reporting this!
I will look into it. Do you have any error description?

**Comment by Danielshmaniel** [comment]
@CaptainDario thank you too, however i don't think i can see any error messages, it just closes by itself without notice.

**Comment by CaptainDario** [comment]
It seems like this is a bug in the mediamediakit package.

**Comment by CaptainDario** [comment]
https://github.com/media-kit/media-kit/issues/861

**Comment by gloaming** [comment]
@CaptainDario If it's possible, can you please roll the Microsoft Store release back to the previous version?

**Comment by CaptainDario** [comment]
I would like to, but I can not build a working package anymore even if I revert everything back to the old release.
I think I will find a workaround on the weekend. Sorry for the inconvenience. 
Until then, you can use the exe release from GitHub.

**Comment by CaptainDario** [comment]
Found a workaround, will publish a release in the next 24h.

**Comment by CaptainDario** [comment]
@gloaming @Danielshmaniel I uploaded a new version that fixes it on my machine, could you give it a try and let me know?
You can download it from [here](https://github.com/CaptainDario/DaKanji/releases/tag/v3.4.2b2)

**Comment by Danielshmaniel** [comment]
@CaptainDario it works when i tried the fixed version of the zip file.

**Comment by Danielshmaniel** [comment]
@CaptainDario actually, i found that the 'Drawing' section is blank in this version: 
![image](https://github.com/CaptainDario/DaKanji/assets/85984021/f02b43ce-f54d-4d21-96c5-3735827c9bc5)

**Comment by CaptainDario** [comment]
Thank you for letting me know that it starts again. I will fix the drawing issue.

**Comment by CaptainDario** [comment]
The drawing [should also be fixed](https://github.com/CaptainDario/DaKanji/releases/tag/v3.4.2b3), if you can confirm it works now I will create a new store release.

**Comment by Danielshmaniel** [comment]
@CaptainDario the fix works, thanks, you're all set now.

**Comment by CaptainDario** [comment]
It is in certification now, should be available soon in the MS Store.

**Comment by CaptainDario** [comment]
@Danielshmaniel @gloaming it should now be available in the store

**Comment by CaptainDario** [comment]
@Danielshmaniel @gloaming If the latest release fixes it please let me know.

**Comment by CaptainDario** [comment]
Seems to be solved
